version: "3.7"
services:

    nginx:
        build:
            context: ../image
            target: nginx
            dockerfile: docker/Dockerfile
        image: myproject/nginx_app:${BUILD_TAG:-latest}
        environment:
            FCGI_SERVER_HOST: "${FCGI_SERVER_HOST:-php}"
            FCGI_SERVER_PORT: "${FCGI_SERVER_PORT:-9000}"
        ports:
            - "${APP_WEB_PORT:-80}:80"

    php:
        build:
            context: ../image
            target: php
            dockerfile: docker/Dockerfile
        image: myproject/php_app:${BUILD_TAG:-latest}
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: "${PHP_OPCACHE_VALIDATE_TIMESTAMPS:-on}"

    database:
        image: mysql/mysql-server:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD:-dbpass}
            MYSQL_USER: ${MARIA_USER:-dbuser}
            MYSQL_PASSWORD: ${MARIA_PASSWORD:-dbpass}
            MYSQL_DATABASE: ${MARIA_DATABASE:-dbname}
