parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller'
        tags: ['controller.service_arguments']

    Infrastructure\:
        resource: '../src/Infrastructure/'
        exclude: '../src/Infrastructure/Symfony/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
